from . import db
from flask_login import UserMixin
from datetime import datetime


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    firstname = db.Column(db.String(25))
    middlename = db.Column(db.String(25))
    lastname = db.Column(db.String(25))
    age = db.Column(db.Integer)
    address = db.Column(db.String(50))
    contact = db.Column(db.String(15))
    email = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(100))
    marital = db.Column(db.String(25))
    educ = db.Column(db.String(25))
    employ = db.Column(db.String(25))
    income = db.Column(db.String(25))
    sdp1 = db.Column(db.String(5))
    sdp2 = db.Column(db.String(5))
    sdp3 = db.Column(db.String(5))
    sdp4 = db.Column(db.String(5))
    sdp5 = db.Column(db.String(5))
    sdp6 = db.Column(db.String(5))
    sdp7 = db.Column(db.String(5))
    sdp8 = db.Column(db.String(5))
    sdp9 = db.Column(db.String(5))
    numpreg = db.Column(db.Integer)
    livechild = db.Column(db.Integer)
    numpremature = db.Column(db.Integer)
    nummiscarriage = db.Column(db.Integer)
    obscore = db.Column(db.Integer)
    comor = db.Column(db.String(25))
    delivery = db.Column(db.String(25))
    pr1 = db.Column(db.String(5))
    pr2 = db.Column(db.String(5))
    pr3 = db.Column(db.String(5))
    compli = db.Column(db.String(25))
    ill = db.Column(db.String(25))
    is_assess = db.Column(db.Boolean, default=False, nullable=False)
    epds_score = db.Column(db.Integer)
    date_submitted = db.Column(db.Date)
    file = db.Column(db.LargeBinary)
    messages = db.relationship('ChatHistory', backref='user', lazy=True)

class ChatHistory(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    message = db.Column(db.String(1000))
    by = db.Column(db.String(24), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    date_send = db.Column(db.DateTime, default=datetime.utcnow)
 
class User_health(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    firstname = db.Column(db.String(25))
    middlename = db.Column(db.String(25))
    lastname = db.Column(db.String(25))
    address = db.Column(db.String(50))
    contact = db.Column(db.String(15))
    date_submitted = db.Column(db.Date)
    condition = db.Column(db.String(50))
    state = db.Column(db.String(25))

class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(25))
    email = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(100))
